import NiceTry.Fors.Bridge.YulParser

namespace NiceTry.Fors.Bridge

def pinnedForsOptimizedYulTokenChunks : List (List YulParser.Token) :=
  [[NiceTry.Fors.Bridge.YulParser.Token.ident "object",
  NiceTry.Fors.Bridge.YulParser.Token.string "ForsVerifier_240",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "code",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memoryguard",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "callvalue",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let"],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "datasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.string "ForsVerifier_240_deployed",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "codecopy",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "dataoffset",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.string "ForsVerifier_240_deployed",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "object",
  NiceTry.Fors.Bridge.YulParser.Token.string "ForsVerifier_240_deployed",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "code",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore"],
 [NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memoryguard",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "iszero",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "lt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "switch",
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 224,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "case"],
 [NiceTry.Fors.Bridge.YulParser.Token.number 447575493,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "callvalue",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "slt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "offset",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "gt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 18446744073709551615,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "iszero",
  NiceTry.Fors.Bridge.YulParser.Token.lparen],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "slt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 35,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "length",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "offset"],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "gt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "length",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 18446744073709551615,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "gt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "length",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 36,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "fun_recover",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 36,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "length",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 36,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let"],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "memPos",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sub",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 160,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 32],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "case",
  NiceTry.Fors.Bridge.YulParser.Token.number 669619007,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "callvalue",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "slt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma],
 [NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "constant_FORS_SIG_LEN",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_1",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_1",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_1"],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "case",
  NiceTry.Fors.Bridge.YulParser.Token.number 2838645039,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "callvalue",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "slt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_2",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 26,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_2",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "case",
  NiceTry.Fors.Bridge.YulParser.Token.number 3387237855,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "callvalue",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "slt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_3",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_3",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 16,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_3",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "case",
  NiceTry.Fors.Bridge.YulParser.Token.number 4098277840,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if"],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "callvalue",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "slt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldatasize",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_4",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_4",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 5,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "memPos_4",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "function",
  NiceTry.Fors.Bridge.YulParser.Token.ident "constant_FORS_SIG_LEN",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.arrow,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 96,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 2400,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "ret_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "gt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 224,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1313373041],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 17,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 36,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 48,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "gt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum_1",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 224,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1313373041,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 17,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 36,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum_1",
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "function",
  NiceTry.Fors.Bridge.YulParser.Token.ident "fun_recover",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_offset"],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_length",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_digest",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.arrow,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "expr",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "constant_FORS_SIG_LEN",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 32,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 96,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 2400,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product",
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "gt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "sum",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 224,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1313373041,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 17,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "revert",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 36,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_3",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_3",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "iszero",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "eq",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_length",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "expr",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "leave",
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$pkSeed",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 16,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$pkSeed",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_offset",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_digest",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 2,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "product"],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dVal",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 160,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "if",
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 125,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dVal",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 31],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$pkSeed",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "var_sig_offset",
  NiceTry.Fors.Bridge.YulParser.Token.comma],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$rootPtr",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$tLeafBase",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dVal",
  NiceTry.Fors.Bridge.YulParser.Token.ident "for",
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "lt",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 25,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$rootPtr",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$rootPtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$tLeafBase",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$tLeafBase",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 5,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.lbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 928,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$tLeafBase",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 31,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 960,
  NiceTry.Fors.Bridge.YulParser.Token.comma],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s"],
 [NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 5,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 928,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 1],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 15,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1020847100762815390390123822299599601664,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 960,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 992,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and"],
 [NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 16,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_1",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 31,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 480,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 928],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 2,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 7,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1020847100762815390390123822303894568960,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen],
 [NiceTry.Fors.Bridge.YulParser.Token.number 960,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_1",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_1",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 992,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_1",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_2",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.comma],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 31,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 224,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 928,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 2,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr"],
 [NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 3,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1020847100762815390390123822308189536256,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 960,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 992,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 48,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_3",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not"],
 [NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_3",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 2,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 31,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret_2",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore"],
 [NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 928,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shr",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 4,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1020847100762815390390123822312484503552,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 960,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_3",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_3",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 992,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_3",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen],
 [NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_4",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "let",
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_4",
  NiceTry.Fors.Bridge.YulParser.Token.assign,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen],
 [NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$dCursor",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 31,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 928,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "or",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$t",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1020847100762815390390123822316779470848,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 960],
 [NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_4",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$node_4",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "xor",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 992,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$s_4",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "calldataload",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "add",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$treePtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 80,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "usr$rootPtr",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 896,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 128,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 130,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 864,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "not",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 340282366920938463463374607431768211455,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "mstore",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "and",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "keccak256",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 64,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma],
 [NiceTry.Fors.Bridge.YulParser.Token.ident "sub",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "shl",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 160,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.number 1,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.ident "return",
  NiceTry.Fors.Bridge.YulParser.Token.lparen,
  NiceTry.Fors.Bridge.YulParser.Token.number 0,
  NiceTry.Fors.Bridge.YulParser.Token.comma,
  NiceTry.Fors.Bridge.YulParser.Token.ident "ret",
  NiceTry.Fors.Bridge.YulParser.Token.rparen,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.ident "data",
  NiceTry.Fors.Bridge.YulParser.Token.string ".metadata",
  NiceTry.Fors.Bridge.YulParser.Token.hexString
    "a2646970667358221220b025656c5ffb71c940c16f707dacbd0917f63d0fd53e10d2e0128bf4b9340fa864736f6c634300081e0033",
  NiceTry.Fors.Bridge.YulParser.Token.rbrace,
  NiceTry.Fors.Bridge.YulParser.Token.rbrace]]

def pinnedForsOptimizedYulTokens : List YulParser.Token :=
  pinnedForsOptimizedYulTokenChunks.flatten

end NiceTry.Fors.Bridge
